
plugins_dir:
  - jekyll-mentions

title: Cactus / OM#
description: Visual Programming | Computer-Aided Music Compositon

show_downloads: false

site.url: https://cac-t-u-s.github.io/om-sharp/

owner_url: https://github.com/j-bresson
owner_name: j-bresson
